import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { Inter } from "@next/font/google";
import Image from "next/image";

import Carousel from "react-bootstrap/Carousel";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";

/*====image===== */
import slider1 from "../public/image/slider1.jpg";
import slider2 from "../public/image/slider2.jpg";
import slider3 from "../public/image/slider3.jpg";
import fbLogo from "../public/image/Facebook.png";
import httpIcon from "../public/image/social/http.jpg";
import activityIcon from "../public/image/social/activity.jpg";
import noticeIcon from "../public/image/social/1.jpg";
import socialIcon from "../public/image/social/social.png";
import president from "../public/image/profile/president.jpg";
import secretary from "../public/image/profile/Secretary.jpg";
import vision from "../public/image/vision.jpg";
import mission from "../public/image/mission.jpg";

import {
  FaPause,
  FaPlay,
  FaNetworkWired,
  FaCalendarAlt,
  FaWindows,
  FaFacebookSquare,
  FaHandshake,
  FaEye,
  FaPodcast,
  FaCodepen,
  FaChevronRight,
} from "react-icons/fa";

import { GiArcheryTarget } from "react-icons/gi";

import ImageGallery from "../components/ImageGallery";
import { Button } from "react-bootstrap";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [marqueeActive, setMarqueeActive] = useState(false);

  const marqueeToggle = () => {
    setMarqueeActive(!marqueeActive);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="hero-banner-section">
        <div className="container">
          <div className="row g-0">
            <div className="col-md-12">
              <Carousel>
                <Carousel.Item>
                  <Image
                    className="d-block w-100"
                    src={slider1}
                    height={640}
                    objectFit="full"
                    alt="First slide"
                  />
                  <Carousel.Caption>
                   
                    <h3>
                    Pioneering  to sustainable aerospace for a safe and united world
                    </h3>
                  </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item>
                  <Image
                    className="d-block w-100"
                    src={slider2}
                    height={640}
                    alt="Second slide"
                  />

                  <Carousel.Caption>
                    <h3>
                    If you can walk away from a landing,
                    its a good landing. If you use the airplane the next day, its an outstanding landing.
                    </h3>
                  </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item>
                  <Image
                    className="d-block w-100"
                    src={slider3}
                    height={640}
                    objectFit="cover"
                    alt="Third slide"
                  />

                  <Carousel.Caption>
                    
                    <h3>
                    Rules are made for people who arent willing to make up their own.
                    </h3>
                  </Carousel.Caption>
                </Carousel.Item>
              </Carousel>
            </div>
            {/* <div className="col-md-2">
              <div className="management-profile">
                <div className="card text-white my-4 bg-transparent border-0 d-flex align-items-center text-center">
                  <Image src={president} height={150} width={150} alt="..." />
                  <div className="card-body">
                    <p className="member-name mb-0" title="Md. Saidur Rahman">Md. Saidur Rahman</p>
                    <p className="mb-0">President</p>
                    <Link href="/about/president">
                      <Button
                        className="mt-2 w-75"
                        variant="light"
                        size="sm"
                      >
                        Message
                      </Button>
                    </Link>
                  </div>
                </div>

                <div className="card text-white my-4 bg-transparent  border-0 d-flex align-items-center text-center">
                  <Image src={secretary} height={150} width={150} alt="..." />
                  <div className="card-body">
                    <p className="member-name mb-0" title="Abu Noman Md.Zakir Hossain">
                      Abu Noman Md.Zakir Hossain
                    </p>
                    <p className="mb-0">General Secretary</p>
                    <Link href="/about/secretry">
                      <Button
                        className="mt-2 w-75"
                        variant="light"
                        size="sm"
                      >
                        Message
                      </Button>
                    </Link>
                  </div>
                </div>
              </div>
            </div> */}
          </div>
        </div>
      </section>

      <section className="welcome-caption-section">
        <div className="container">
          <article className="welcome-article">
            <a href="#">
              <h3 className="mb-4">
              A world leading manufacturer of business jets
              </h3>
              <p>
                Our business jets are the most comprehensive in the industry, with two leading aircraft families Challenger and Global. These jets allow our customers to grow within the Bombardier business aircraft family as their travel requirements evolve.
              </p>
              <ul>
                <li className="mb-3">
                  <data value="21053">
                  Since its inception, Bombardiers focus has always been on helping the world move efficiently and quickly through highly reliable transportation products, whether on the ground or in the air.
                  </data>
                </li>
                <li className="mb-3">
                  <data value="21054">
                    
                  Today, we are a world leading manufacturer of business aircraft with a global network of service centres. We masterfully design private jes and signature moments. We make it happen through an extensive portfolio of innovative products and every day, our planes move thousands of people around the globe quickly, safely and efficiently.
                  </data>
                </li>
                <li className="mb-3">
                  <data value="21055">
                    Messages and correspondences to and from the executive body
                    to all concerned electronically generated through the
                    website. We do not want to see misuseabuse of the
                    Association Letterhead pad anymore.
                  </data>
                </li>
              </ul>
            </a>
          </article>

          <div className="latest-news-list">
            <div className="d-flex flex-column justify-content-center align-items-center">
              <h3 className="text-uppercase">Who We Are</h3>
              <p>
              We are committed to building our products with the future in mind  making them reliable and more efficient
              </p>
            </div>

            <div className="row">
              <div className="col-md-12">
              <div className="row row-cols-1 row-cols-md-2 align-items-md-center g-5 py-5">
                <div className="col d-flex flex-column align-items-start gap-2">
                  <h3 className="fw-bold">A world leading manufacturer of business jets</h3>
                  <p className="text-muted">Since its inception, Bombardiers focus has always been on helping the world move efficiently and quickly through highly reliable transportation products, whether on the ground or in the air</p>
                  <a href="#" className="btn btn-primary btn-lg">Know More</a>
                </div>

                <div className="col">
                  <div className="row row-cols-1 row-cols-sm-2 g-4">
                    <div className="col d-flex flex-column gap-2">
                      <div className="feature-icon-small d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-4 rounded-3">
                      
                      </div>
                      <h4 className="fw-semibold mb-0">Our governance</h4>
                      <p className="text-muted">Bombardier believes that strong corporate governance is linked to strong corporate performance.</p>
                    </div>

                    <div className="col d-flex flex-column gap-2">
                      <div className="feature-icon-small d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-4 rounded-3">
                       
                      </div>
                      <h4 className="fw-semibold mb-0">Our history</h4>
                      <p className="text-muted">Celebrating  80 years of creativity, growth and a relentless desire to innovate, Bombardier has grown...</p>
                    </div>

                    <div className="col d-flex flex-column gap-2">
                      <div className="feature-icon-small d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-4 rounded-3">
                       
                      </div>
                      <h4 className="fw-semibold mb-0">Our Code of Ethics</h4>
                      <p className="text-muted">We owe it to our customers, to our shareholders and to each other to always uphold the highest standards ...</p>
                    </div>

                    <div className="col d-flex flex-column gap-2">
                      <div className="feature-icon-small d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-4 rounded-3">
                       
                      </div>
                      <h4 className="fw-semibold mb-0">Supplier Code of Conduct</h4>
                      <p className="text-muted">Bombardier believes that good ethics and a strong commitment to corporate responsibility and sustainable ...</p>
                    </div>
                  </div>
                </div>
                </div>
            
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="social-media-section">
        <div className="container">
          <div className="row">
            <div className="col-md-3">
              <div className="article-container">
                <div className="article-img-holder">
                  <Image
                    src={noticeIcon}
                    className="card-img-top social-img"
                    alt="comon"
                  />
                </div>

                <Link className="article-title-link" href="#">
                  <div className="media-icon">
                    <FaCalendarAlt></FaCalendarAlt>
                  </div>
                  <p className="card-text">Notice Board</p>
                </Link>
              </div>
            </div>

            <div className="col-md-3">
              <div className="article-container">
                <div className="article-img-holder">
                  <Image
                    src={noticeIcon}
                    className="card-img-top social-img"
                    alt="comon"
                  />
                </div>

                <Link className="article-title-link" href="#">
                  <div className="media-icon">
                    <FaHandshake></FaHandshake>
                  </div>
                  <p className="card-text">Notice Board</p>
                </Link>
              </div>
            </div>

            <div className="col-md-3">
              <div className="article-container">
                <div className="article-img-holder">
                  <Image
                    src={noticeIcon}
                    className="card-img-top social-img"
                    alt="comon"
                  />
                </div>

                <Link className="article-title-link" href="#">
                  <div className="media-icon">
                    <FaWindows></FaWindows>
                  </div>
                  <p className="card-text">Notice Board</p>
                </Link>
              </div>
            </div>

            <div className="col-md-3">
              <div className="article-container">
                <div className="article-img-holder">
                  <Image
                    src={noticeIcon}
                    className="card-img-top social-img"
                    alt="comon"
                  />
                </div>

                <Link className="article-title-link" href="#">
                  <div className="media-icon">
                    <FaNetworkWired></FaNetworkWired>
                  </div>
                  <p className="card-text">Notice Board</p>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="gallery-section">
        <div className="container">
          <ImageGallery />
        </div>
      </section>

      <section className="mission-vision-section">
        <div className="container" id="featured-3">
          <h3 className="text-center text-uppercase section-title">
            Our Vision and Mission
          </h3>
          <div className="row mt-5">
            <div className="feature col">
              <FaEye className="title-icon"></FaEye>
              {/* <Image
                src={vision}
                height={100}
                width={100}
                className="card-img-top social-img"
                alt="comon"
              /> */}
              <h2 className="py-3">Vision</h2>
              <p>
                Paragraph of text beneath the heading to explain the heading.
                Well add onto it with another sentence and probably just keep
                going until we run out of words.
              </p>
              <a href="#" className="icon-link text-primary">
                Know More
                <svg className="bi" width="1em" height="1em">
                  <FaChevronRight />
                </svg>
              </a>
            </div>
            <div className="feature col">
              <GiArcheryTarget className="title-icon"></GiArcheryTarget>
              {/* <Image
                src={mission}
                height={100}
                width={100}
                className="card-img-top social-img"
                alt="comon"
              /> */}
              <h2 className="py-3">Mission</h2>
              <p>
                Paragraph of text beneath the heading to explain the heading.
                Well add onto it with another sentence and probably just keep
                going until we run out of words.
              </p>
              <a href="#" className="icon-link text-primary">
                Know More
                <svg className="bi" width="1em" height="1em">
                  <FaChevronRight />
                </svg>
              </a>
            </div>
            <div className="feature col">
              <FaCodepen className="title-icon"></FaCodepen>
              <h2 className="py-3">Values</h2>
              <p>
                Paragraph of text beneath the heading to explain the heading.
                Well add onto it with another sentence and probably just keep
                going until we run out of words.
              </p>
              <a href="#" className="icon-link text-primary">
                Know More
                <svg className="bi" width="1em" height="1em">
                  <FaChevronRight />
                </svg>
              </a>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
