import Head from "next/head";
import React from "react";
import SecretryMessage from "../../../components/Message/Secretry";

const SecretryInfo = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="section-padding">
        <div className="container">
          <h2 className="text-center text-uppercase section-title">
            General Secretry Message
          </h2>
          <div className="introduction-section mt-5">
            <SecretryMessage />
          </div>
          <div className="details-information mt-5">
            <div className="container">
              <p>
                In this endeavor, I would like to congratulate my colleagues of
                the present executive committee who have shown the character to
                embrace the association and its challenges as an integral part
                of their life. With the continuous support and dedication of
                members, I am confident that we can achieve our common goals by
                properly developing our resources and being steadfast in
                addressing the pressing challenges. I am sure we will have
                plenty of achievements to share with the esteemed members of
                this association.
              </p>
              <p>
                Merchant Mariners are one of those neglected professionals, who
                have often been overlooked not only by international
                organizations but also by their own countries. The tough
                lifestyle we live and the hardships we endure at sea to make
                sure the world and its people continue to enjoy their life
                onshore. We:-
              </p>

              <ol>
                <li>
                  <strong>Run&nbsp;</strong>the Global Economy.
                </li>
                <li>
                  <strong>Sacrifice&nbsp;</strong>our Social Life.
                </li>
                <li>
                  <strong>Fight&nbsp;</strong>the Toughest Seas and Roughest
                  Weather.
                </li>
                <li>
                  <strong>Risk&nbsp;</strong>our Lives through Piracy and War
                  Zones.
                </li>
                <li>
                  <strong>Face&nbsp;</strong>Extreme Health Hazards.
                </li>
                <li>
                  <strong>Follow&nbsp;</strong>Toughest Regulations and Laws.
                </li>
                <li>
                  <strong>Work Round&nbsp;</strong>the Clock with Monotonous
                  Routines.
                </li>
                <li>
                  <strong>Work the Most&nbsp;</strong>without the Basic Rights.
                </li>
                <li>
                  Are at&nbsp;<strong>High Risk&nbsp;</strong>of&nbsp;
                  <strong>Criminalization and Abandonment </strong>While
                  Performing our Duties.
                </li>
                <li>
                  <strong>Live&nbsp;</strong>with modest Accommodation and
                  Communication Facilities even in these modern days of science
                  &amp; technology.
                </li>
              </ol>

              <p>
              bombardier jets can help us relieve those pressures and give us the
                platform/opportunity to stay connected to those seniors,
                juniors, friends, family, and other fellow mariners of
                Bangladesh.
              </p>
              <ol>
                <li>
                  Promote good industrial relations between members &amp; their
                  employers.
                </li>
                <li>
                  Improve the working condition of members &amp; enhance their
                  financial &amp; social status.
                </li>
                <li>
                  Advance the social, cultural, recreational &amp; educational
                  aspects of members.
                </li>
                <li>
                  Work together with other leading unions around the world to
                  enhance activities &amp; vice-versa.
                </li>
                <li>
                  Maintain affiliation with International Traffic Workers
                  Federation (ITF), London, UK.
                </li>
                <li>
                  Liaise &amp; work with Government &amp; International bodies
                  including IMO, ILO, and ICS, etc in order to take part in
                  developing the shipping sector in Bangladesh.
                </li>
                <li>
                  Share the latest &amp; modern knowledge related to shipping
                  &amp; other subjects among the community &amp; Government
                  bodies.
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SecretryInfo;
